# Generated by Django 4.0.4 on 2022-06-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10000)),
                ('Newsurl', models.CharField(max_length=10000)),
                ('Imageurl', models.CharField(max_length=10000)),
                ('publishedAt', models.CharField(max_length=1000)),
            ],
        ),
    ]
