# Generated by Django 4.0.4 on 2022-06-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsvibes', '0002_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='Imageurl',
            field=models.CharField(default=None, max_length=10000),
        ),
        migrations.AlterField(
            model_name='news',
            name='Newsurl',
            field=models.CharField(default=None, max_length=10000),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(default=None, max_length=10000),
        ),
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
