# Generated by Django 4.0.4 on 2022-06-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsvibes', '0003_news_likes_alter_news_imageurl_alter_news_newsurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Imageurl',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Newsurl',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='publishedAt',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
