# Generated by Django 4.0.4 on 2022-07-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsvibes', '0008_alter_person_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
    ]
