# Generated by Django 4.0.4 on 2022-07-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsvibes', '0011_remove_person_password_remove_person_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
