# Generated by Django 4.0.4 on 2022-07-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsvibes', '0012_person_password_person_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='token',
            field=models.CharField(max_length=10),
        ),
    ]
